return {}
-- return {
-- 	"mrjones2014/smart-splits.nvim",
-- 	-- dependencies = {
-- 	-- 	"mrjones2014/legendary.nvim",
-- 	-- },
-- 	config = function()
-- 		vim.keymap.set("n", "<C-h>", require("smart-splits").move_cursor_left)
-- 		vim.keymap.set("n", "<C-j>", require("smart-splits").move_cursor_down)
-- 		vim.keymap.set("n", "<C-k>", require("smart-splits").move_cursor_up)
-- 		vim.keymap.set("n", "<C-l>", require("smart-splits").move_cursor_right)
-- 		-- require("legendary").setup({
-- 		-- 	extensions = {
-- 		-- 		-- default settings shown below:
-- 		-- 		smart_splits = {
-- 		-- 			directions = { "h", "j", "k", "l" },
-- 		-- 			mods = {
-- 		-- 				-- for moving cursor between windows
-- 		-- 				move = "<C>",
-- 		-- 				-- for resizing windows
-- 		-- 				resize = "<M>",
-- 		-- 				-- for swapping window buffers
-- 		-- 				swap = false, -- false disables creating a binding
-- 		-- 			},
-- 		-- 		},
-- 		-- 	},
-- 		-- })
-- 	end,
-- }
